config/routes.rb
StoreApp::Application.routes.draw do
  root :to => "main#home"
  
  match '/register', :to => 'members#new'
  match '/about', :to => 'pages#about' 
  match '/contact', :to => 'pages#contact'
  match '/sales', :to => 'pages#sales'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  layout :home
  
  def home
  end

end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  
  def new
    @title = "Register"
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def about
    @title = "About"
  end

  def contact
    @title = "Contact"
  end

  def sales
    @title = "Sales"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  # Return a title on a per-page basis.
  def title
      base_title = "Entree"
      if @title.nil?
        base_title
      else
        "#{base_title} | #{@title}"
      end
    end
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.haml
%footer
  %nav.round
    %ul
      %li #{link_to "about", about_path}
      %li #{link_to "contact", contact_path}

app/views/layouts/_header.html.haml
%header
  = link_to image_tag("entree_logo.png", :alt => "Entree", :class => "round"), sales_path
  %nav.round
    %ul
      %li #{link_to "sales", sales_path}

app/views/layouts/_home.html.haml
!!!
%html
  %head
    %title #{title}
    = stylesheet_link_tag 'compiled/home.css', :media => 'screen'
    %header
      = image_tag("entree_logo.png", :alt => "Entree", :class => "gold")
    %body
      .container
      %nav.enter
        %ul
          %li #{link_to "Register", register_path, :class => "register_button sqr"}
    %footer
      %nav.round
        %ul
          %li #{link_to "about", about_path}
          %li #{link_to "contact", contact_path}

app/views/layouts/_stylesheets.html.haml
= stylesheet_link_tag 'compiled/custom.css', :media => 'screen'
 

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title #{title}
    = javascript_include_tag :defaults 
    = csrf_meta_tag 
    = render 'layouts/stylesheets'
  %body
    .container
      = render 'layouts/header'

      %section.round
        #{yield} 

      =render 'layouts/footer'

app/views/main/home.html.haml
= render 'layouts/home'

app/views/members/new.html.haml
%h1 Members#new
%p Find me in app/views/members/new.html.erb

app/views/pages/about.html.haml
%h1 About Entree
%p Entree is an online fashion company focused on providing deeply discounted sales to its members.

app/views/pages/contact.html.haml
%h1 Contact Us
%p blaine@entreelife.com

app/views/pages/sales.html.haml
%h3 Sales
	  